<?php
/**
 * Translation map for ru-RU
 */
return [
    'Fields' => 'Поля',

    'Label' => 'Подпись',
    'Code' => 'Код',
    'Type' => 'Тип',
    'Active' => 'Активность',
    'In list' => 'В списке',
    'Sort' => 'Сортировка',
    'Description' => 'Описание',
    'Multiple' => 'Множественное',
    'Default value' => 'По-умолчанию',
    'Extra HTML-attributes' => 'Дополнительные HTML-атрибуты',
    'Modified' => 'Изменено',
    'Validators' => 'Валидаторы',
    'Values' => 'Значения',
    'Mult.' => 'Множ.',
    'Act.' => 'Акт.',
    'Sort.' => 'Сорт.',

    'Edit field' => 'Изменение поля',
    'New field' => 'Новое поле',
    'Copy field' => 'Копирование поля',

    'Required fields' => 'Обязательные поля',

    'Create' => 'Создать',
    'Edit' => 'Изменить',
    'Copy' => 'Копировать',
    'Copy (with relatives)' => 'Копировать (со связями)',
    'Delete' => 'Удалить',
    'Refresh' => 'Обновить',

    'Properties' => 'Свойства',
    'Settings' => 'Настройки',
    'Extra' => 'Дополнительно',

    'Whether field is displayed.' => 'Отображать поле в форме.',
    'Can accept multiple values.' => 'Может принимать несколько значений.',
    'Display field in results` list.' => 'Отображать в списке результатов.',
    'Up to 250 characters length.' => 'Не более 250 символов длиной.',
    'Valid characters is latin letters, numbers and underscore. Will be autogenerated if no value provided.' => 'Допускаются символы A-Z, 0-9 и "_". По-умолчанию автоматически генерируется.',
    'The numerical value that determines the position of the field in various lists. Default value is `100`.' => 'Числовое значение, определяющее позицию поля в списках.',
    'Affects how the field is rendered and validated.' => 'Влияет на отображение поля и его правила валидации.',
    'Default value is used when no value is set.' => 'Используется, когда значение не указано.',
    'Provide valid JSON-string, ex. {"name": "value"}.' => 'Введите валидную JSON-строку, напр. {"name": "value"}.',

    '{attribute} is required.' => 'Поле {attribute} обязательно для заполнения.',
    'Maximum {max, number} characters allowed.' => 'Допускается не более {max, number} символов.',
    'Value must be greater or equal than {min, number}.' => 'Значение должно быть не меньше {min, number}.',
    'Value must be a integer.' => 'Значение должно быть целым числом.',
    'Invalid code.' => 'Неверный код.',
    'This code is reserved.' => 'Этот код уже используется.',
    '{type} can not be assigned to `multiple` fields.' => 'Тип `{type}` не может быть назначен `множественному` полю.',
    'Only text fields can be displayed in lists.' => 'Только текстовые поля могут отображаться в списках.',

    'String' => 'Строка',
    'Text' => 'Текст',
    'Select' => 'Поле выбора',
    'List' => 'Список выбора',
    'File' => 'Файл',
];