<?php

namespace mail\models;

use app\components\behaviors\PrimaryKeyBehavior;
use app\components\behaviors\WorkflowBehavior;
use app\models\Site;
use app\models\Workflow;
use yii\data\ActiveDataProvider;
use yii\db\ActiveRecord;
use yii\validators\EmailValidator;

/**
 * Class Template
 *
 * @property string $uuid
 * @property string $code
 * @property string $from
 * @property string $to
 * @property string $reply_to
 * @property string $copy
 * @property string $subject
 * @property string $text
 * @property string $html
 * @property string $workflow_uuid
 *
 * @property Site[] $sites
 * @property Type $type
 * @property Workflow $workflow
 *
 * @package mail\models
 */
class Template extends ActiveRecord
{
    /**
     * Message format switch.
     * @var string
     */
    public $format = 'text';
    /**
     * @var string
     */
    private $_type;
    /**
     * @var array
     */
    private $_sites;

    /**
     * @return string
     */
    public static function tableName()
    {
        return '{{%mail_templates}}';
    }

    /**
     * @param $message
     * @param array $params
     * @return string
     */
    public static function t($message, $params = [])
    {
        return \Yii::t('mail', $message, $params);
    }

    /**
     * @return array
     */
    public function attributeLabels(): array
    {
        $labels = [
            'subject' => 'Subject',
            'code' => 'Code',
            'from' => 'From',
            'to' => 'To',
            'reply_to' => 'Reply to',
            'copy' => 'Copy',
            'text' => 'Plain text',
            'html' => 'HTML',
            'format' => 'Message format',
            'type' => 'Type',
            'sites' => 'Sites',
            'workflow.modified_date' => 'Modified',
        ];

        return array_map('self::t', $labels);
    }

    /**
     * @return array
     */
    public function attributeHints(): array
    {
        $hints = [
            'from' => 'Specify the sender of this template.',
            'to' => 'List the recipients of this template.',
            'reply_to' => 'List E-Mail addresses to reply to.',
            'copy' => 'List E-Mail addresses to which send a message`s copy.',
            'sites' => 'Choose sites which can use that template.',
            'code' => 'Valid characters is latin letters, numbers and underscore. Will be autogenerated if no value provided.',
        ];

        return array_map('self::t', $hints);
    }

    /**
     * @return array
     */
    public function rules(): array
    {
        return [
            [['subject', 'to', 'type'], 'required', 'message' => self::t('{attribute} is required.')],
            ['from', 'email', 'allowName' => true, 'message' => self::t('Invalid E-Mail.')],
            [['to', 'reply_to', 'copy'], 'validateRecipient'],
            ['subject', 'string', 'max' => 255, 'tooLong' => self::t('Maximum (max, number) characters allowed.')],
            [['text', 'html'], 'safe'],
            ['sites', 'exist', 'targetClass' => Site::className(), 'targetAttribute' => 'uuid', 'allowArray' => true],
            ['type', 'exist', 'targetClass' => Type::className(), 'targetAttribute' => 'uuid'],
            ['code', 'unique', 'message' => self::t('Template with code `{value}` is already exist.')]
        ];
    }

    /**
     * @param $attribute
     */
    public function validateRecipient($attribute)
    {
        $validator = new EmailValidator();
        $array = preg_split('/[\s,;]+/', $this->$attribute, -1, PREG_SPLIT_NO_EMPTY);
        foreach ($array as $email) {
            if (!$validator->validate($email) && !preg_match('/^\{\{[a-z0-9_]{0,50}\}\}$/i', $email)) {
                $this->addError($attribute, self::t('Invalid E-Mail or field code.'));
            }
        }
    }

    /**
     * @return array
     */
    public function transactions(): array
    {
        return [
            self::SCENARIO_DEFAULT => self::OP_ALL
        ];
    }

    /**
     * @return array
     */
    public function behaviors(): array
    {
        $behaviors = parent::behaviors();
        $behaviors[] = PrimaryKeyBehavior::className();
        $behaviors[] = WorkflowBehavior::className();

        return $behaviors;
    }

    /**
     * @param TemplateSettings|\app\models\UserSettings $settings
     * @return ActiveDataProvider
     */
    public static function search($settings)
    {
        $defaultOrder = ['workflow.modified_date' => SORT_DESC];
        if ($settings) {
            $defaultOrder = [$settings->sortBy => $settings->sortOrder];
        }

        return new ActiveDataProvider([
            'query' => self::prepareSearchQuery(),
            'sort' => [
                'defaultOrder' => $defaultOrder,
                'attributes' => self::getSortAttributes()
            ]
        ]);
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        $isValid = parent::beforeSave($insert);

        if ($isValid) {
            // Make symbolic code uppercase
            $this->code = mb_strtoupper($this->code);

            // Purify HTML-content
            $this->html = \Yii::$app->formatter->asHtml($this->html);
        }

        return $isValid;
    }

    /**
     * @inheritdoc
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);

        if ($this->_type) {
            $this->insertType();
        }

        if ($this->_sites) {
            $this->insertSites();
        }
    }

    /**
     * Insert template type.
     */
    protected function insertType()
    {
        TemplateType::deleteAll(['template_uuid' => $this->uuid]);

        (new TemplateType([
            'template_uuid' => $this->uuid,
            'type_uuid' => $this->_type
        ]))->insert();
    }

    /**
     * Insert templates sites.
     */
    protected function insertSites()
    {
        TemplateSite::deleteAll(['template_uuid' => $this->uuid]);

        foreach ($this->_sites as $site) {
            (new TemplateSite([
                'template_uuid' => $this->uuid,
                'site_uuid' => $site
            ]))->insert();
        }
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSites()
    {
        if ($this->_sites === null) {
            $this->_sites = $this->hasMany(Site::className(), ['uuid' => 'site_uuid'])
                ->viaTable(TemplateSite::tableName(), ['template_uuid' => 'uuid']);
        }

        return $this->_sites;
    }

    /**
     * @param array $sites
     */
    public function setSites($sites)
    {
        $this->_sites = $sites;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getType()
    {
        if ($this->_type === null) {
            $this->_type = $this->hasOne(Type::className(), ['uuid' => 'type_uuid'])
                ->viaTable(TemplateType::tableName(), ['template_uuid' => 'uuid']);
        }

        return $this->_type;
    }

    /**
     * @param string $type
     */
    public function setType($type)
    {
        $this->_type = $type;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorkflow()
    {
        return $this->hasOne(Workflow::className(), ['uuid' => 'workflow_uuid']);
    }

    /**
     * @return Template
     */
    public function duplicate()
    {
        $copy = new self([
            'sites' => $this->sites,
            'type' => $this->type
        ]);

        foreach ($this->attributes as $attribute => $value) {
            if ($this->isAttributeSafe($attribute)) {
                $copy->$attribute = $value;
            }
        }

        $appendixLength = 7;
        if (mb_strlen($copy->code) > (100 - $appendixLength)) {
            $copy->code = mb_substr($copy->code, 0, (100 - $appendixLength));
        }

        $copy->code .= '_' . \Yii::$app->security->generateRandomString($appendixLength - 1);

        return $copy;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    protected static function prepareSearchQuery()
    {
        return self::find()->joinWith('workflow');
    }

    /**
     * @return array
     */
    protected static function getSortAttributes(): array
    {
        return [
            'active',
            'subject',
            'code',
            'workflow.modified_date' => [
                'asc' => ['{{%workflow}}.[[modified_date]]' => SORT_ASC],
                'desc' => ['{{%workflow}}.[[modified_date]]' => SORT_DESC],
            ],
        ];
    }
}