<?php

namespace mail\models;

use app\components\behaviors\PrimaryKeyBehavior;
use app\components\behaviors\WorkflowBehavior;
use app\models\Workflow;
use yii\data\ActiveDataProvider;
use yii\db\ActiveRecord;

/**
 * Class Type
 *
 * @property string $uuid
 * @property string $code
 * @property string $title
 * @property string $description
 * @property string $workflow_uuid
 *
 * @property Workflow $workflow
 *
 * @package mail\models
 */
class Type extends ActiveRecord
{
    /**
     * @return string
     */
    public static function tableName()
    {
        return '{{%mail_types}}';
    }

    /**
     * @param $message
     * @param array $params
     * @return string
     */
    public static function t($message, $params = [])
    {
        return \Yii::t('mail', $message, $params);
    }

    /**
     * @return array
     */
    public function attributeLabels(): array
    {
        $labels = [
            'code' => 'Code',
            'title' => 'Title',
            'description' => 'Description',
            'workflow.modified_date' => 'Modified',
        ];

        return array_map('self::t', $labels);
    }

    /**
     * @return array
     */
    public function attributeHints(): array
    {
        $hints = [
            'code' => 'Valid characters is latin letters, numbers and underscore. Will be autogenerated if no value provided.',
        ];

        return array_map('self::t', $hints);
    }

    /**
     * @return array
     */
    public function rules(): array
    {
        return [
            [['code', 'title'], 'required', 'message' => self::t('{attribute} is required.')],
            ['code', 'string', 'max' => 100, 'tooLong' => self::t('Maximum (max, number) characters allowed.')],
            ['title', 'string', 'max' => 255, 'tooLong' => self::t('Maximum (max, number) characters allowed.')],
            ['description', 'safe'],
            ['code', 'unique', 'message' => self::t('Type with code `{value}` is already exist.')]
        ];
    }

    /**
     * @return array
     */
    public function transactions(): array
    {
        return [
            self::SCENARIO_DEFAULT => self::OP_ALL
        ];
    }

    /**
     * @return array
     */
    public function behaviors(): array
    {
        $behaviors = parent::behaviors();
        $behaviors[] = PrimaryKeyBehavior::className();
        $behaviors[] = WorkflowBehavior::className();

        return $behaviors;
    }

    /**
     * @return bool
     */
    public function beforeValidate()
    {
        $isValid = parent::beforeValidate();

        if ($isValid) {
            // Need for valid slug generation
            if (mb_strlen($this->code) > 100) {
                $this->code = mb_substr($this->code, 0, 100);
            }
        }

        return $isValid;
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        $isValid = parent::beforeSave($insert);

        if ($isValid) {
            // Make symbolic code uppercase
            $this->code = mb_strtoupper($this->code);
        }

        return $isValid;
    }

    /**
     * @param \app\models\UserSettings|TypeSettings $settings
     * @return ActiveDataProvider
     */
    public static function search($settings)
    {
        $defaultOrder = ['workflow.modified_date' => SORT_DESC];
        if ($settings) {
            $defaultOrder = [$settings->sortBy => $settings->sortOrder];
        }

        return new ActiveDataProvider([
            'query' => self::prepareSearchQuery(),
            'sort' => [
                'defaultOrder' => $defaultOrder,
                'attributes' => self::getSortAttributes()
            ]
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorkflow()
    {
        return $this->hasOne(Workflow::className(), ['uuid' => 'workflow_uuid']);
    }

    /**
     * @return Type|bool
     */
    public function duplicate()
    {
        $copy = new self();

        foreach ($this->attributes as $attribute => $value) {
            if ($this->isAttributeSafe($attribute)) {
                $copy->$attribute = $value;
            }
        }

        $appendixLength = 7;
        if (mb_strlen($copy->code) > (100 - $appendixLength)) {
            $copy->code = mb_substr($copy->code, 0, (100 - $appendixLength));
        }

        $copy->code .= '_' . \Yii::$app->security->generateRandomString($appendixLength - 1);

        return $copy;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    protected static function prepareSearchQuery()
    {
        return self::find()->joinWith('workflow');
    }

    /**
     * @return array
     */
    protected static function getSortAttributes(): array
    {
        return [
            'title',
            'code',
            'workflow.modified_date' => [
                'asc' => ['{{%workflow}}.[[modified_date]]' => SORT_ASC],
                'desc' => ['{{%workflow}}.[[modified_date]]' => SORT_DESC],
            ],
        ];
    }
}