DELETE FROM {{%addresses_countries}};
INSERT INTO {{%addresses_countries}} (`code`, `title`, `title_ru-RU`) VALUES
('AD', 'Andorra', 'Андорра'),
('AE', 'United Arab Emirates', 'ОАЭ'),
('AF', 'Afghanistan', 'Афганистан'),
('AG', 'Antigua and Barbuda', 'Антигуа и Барбуда'),
('AI', 'Anguilla', 'Ангилья'),
('AL', 'Albania', 'Албания'),
('AM', 'Armenia', 'Армения'),
('AO', 'Angola', 'Ангола'),
('AQ', 'Antarctica', 'Антарктида'),
('AR', 'Argentina', 'Аргентина'),
('AS', 'American Samoa', 'Американское Самоа'),
('AT', 'Austria', 'Австрия'),
('AU', 'Australia', 'Австралия'),
('AW', 'Aruba', 'Аруба'),
('AX', 'Aland Islands', 'Аландские острова'),
('AZ', 'Azerbaijan', 'Азербайджан'),
('BA', 'Bosnia and Herzegovina', 'Босния и Герцеговина'),
('BB', 'Barbados', 'Барбадос'),
('BD', 'Bangladesh', 'Бангладеш'),
('BE', 'Belgium', 'Бельгия'),
('BF', 'Burkina Faso', 'Буркина-Фасо'),
('BG', 'Bulgaria', 'Болгария'),
('BH', 'Bahrain', 'Бахрейн'),
('BI', 'Burundi', 'Бурунди'),
('BJ', 'Benin', 'Бенин'),
('BL', 'Saint Barthelemy', 'Сен-Бартелеми'),
('BM', 'Bermuda', 'Бермуды'),
('BN', 'Brunei Darussalam', 'Бруней'),
('BO', 'Bolivia (Plurinational State of)', 'Боливия'),
('BQ', 'Bonaire, Sint Eustatius and Saba', 'Бонэйр, Синт-Эстатиус и Саба'),
('BR', 'Brazil', 'Бразилия'),
('BS', 'Bahamas', 'Багамы'),
('BT', 'Bhutan', 'Бутан'),
('BV', 'Bouvet Island', 'Остров Буве'),
('BW', 'Botswana', 'Ботсвана'),
('BY', 'Belarus', 'Белоруссия'),
('BZ', 'Belize', 'Белиз'),
('CA', 'Canada', 'Канада'),
('CC', 'Cocos (Keeling) Islands', 'Кокосовые острова'),
('CD', 'Congo (Democratic Republic of the)', 'Демократическая Республика Конго'),
('CF', 'Central African Republic', 'ЦАР'),
('CG', 'Congo', 'Республика Конго'),
('CH', 'Switzerland', 'Швейцария'),
('CI', 'Cote d''Ivoire', 'Кот-д''Ивуар'),
('CK', 'Cook Islands', 'Острова Кука'),
('CL', 'Chile', 'Чили'),
('CM', 'Cameroon', 'Камерун'),
('CN', 'China', 'КНР (Китайская Народная Республика)'),
('CO', 'Colombia', 'Колумбия'),
('CR', 'Costa Rica', 'Коста-Рика'),
('CU', 'Cuba', 'Куба'),
('CV', 'Cabo Verde', 'Кабо-Верде'),
('CW', 'Curacao', 'Кюрасао'),
('CX', 'Christmas Island', 'Остров Рождества'),
('CY', 'Cyprus', 'Кипр'),
('CZ', 'Czechia', 'Чехия'),
('DE', 'Germany', 'Германия'),
('DJ', 'Djibouti', 'Джибути'),
('DK', 'Denmark', 'Дания'),
('DM', 'Dominica', 'Доминика'),
('DO', 'Dominican Republic', 'Доминиканская Республика'),
('DZ', 'Algeria', 'Алжир'),
('EC', 'Ecuador', 'Эквадор'),
('EE', 'Estonia', 'Эстония'),
('EG', 'Egypt', 'Египет'),
('EH', 'Western Sahara', 'САДР'),
('ER', 'Eritrea', 'Эритрея'),
('ES', 'Spain', 'Испания'),
('ET', 'Ethiopia', 'Эфиопия'),
('FI', 'Finland', 'Финляндия'),
('FJ', 'Fiji', 'Фиджи'),
('FK', 'Falkland Islands (Malvinas)', 'Фолклендские острова'),
('FM', 'Micronesia (Federated States of)', 'Микронезия'),
('FO', 'Faroe Islands', 'Фареры'),
('FR', 'France', 'Франция'),
('GA', 'Gabon', 'Габон'),
('GB', 'United Kingdom of Great Britain and Northern Ireland', 'Великобритания'),
('GD', 'Grenada', 'Гренада'),
('GE', 'Georgia', 'Грузия'),
('GF', 'French Guiana', 'Гвиана'),
('GG', 'Guernsey', 'Гернси'),
('GH', 'Ghana', 'Гана'),
('GI', 'Gibraltar', 'Гибралтар'),
('GL', 'Greenland', 'Гренландия'),
('GM', 'Gambia', 'Гамбия'),
('GN', 'Guinea', 'Гвинея'),
('GP', 'Guadeloupe', 'Unofficial  Гваделупа'),
('GQ', 'Equatorial Guinea', 'Экваториальная Гвинея'),
('GR', 'Greece', 'Греция'),
('GS', 'South Georgia and the South Sandwich Islands', 'Южная Георгия и Южные Сандвичевы Острова'),
('GT', 'Guatemala', 'Гватемала'),
('GU', 'Guam', 'Гуам'),
('GW', 'Guinea-Bissau', 'Гвинея-Бисау'),
('GY', 'Guyana', 'Гайана'),
('HK', 'Hong Kong', 'Гонконг'),
('HM', 'Heard Island and McDonald Islands', 'Херд и Макдональд'),
('HN', 'Honduras', 'Гондурас'),
('HR', 'Croatia', 'Хорватия'),
('HT', 'Haiti', 'Гаити'),
('HU', 'Hungary', 'Венгрия'),
('ID', 'Indonesia', 'Индонезия'),
('IE', 'Ireland', 'Флаг Ирландии Ирландия'),
('IL', 'Israel', 'Израиль'),
('IM', 'Isle of Man', 'Остров Мэн'),
('IN', 'India', 'Индия Индия'),
('IO', 'British Indian Ocean Territory', 'Британская территория в Индийском океане'),
('IQ', 'Iraq', 'Ирак'),
('IR', 'Iran (Islamic Republic of)', 'Иран'),
('IS', 'Iceland', 'Исландия'),
('IT', 'Italy', 'Италия'),
('JE', 'Jersey', 'Джерси'),
('JM', 'Jamaica', 'Ямайка'),
('JO', 'Jordan', 'Иордания'),
('JP', 'Japan', 'Япония'),
('KE', 'Kenya', 'Кения'),
('KG', 'Kyrgyzstan', 'Киргизия'),
('KH', 'Cambodia', 'Камбоджа'),
('KI', 'Kiribati', 'Кирибати'),
('KM', 'Comoros', 'Коморы'),
('KN', 'Saint Kitts and Nevis', 'Сент-Китс и Невис'),
('KP', 'Korea (Democratic People''s Republic of)', 'КНДР (Корейская Народно-Демократическая Республика)'),
('KR', 'Korea (Republic of)', 'Республика Корея'),
('KW', 'Kuwait', 'Кувейт'),
('KY', 'Cayman Islands', 'Острова Кайман'),
('KZ', 'Kazakhstan', 'Казахстан'),
('LA', 'Lao People''s Democratic Republic', 'Лаос'),
('LB', 'Lebanon', 'Ливан'),
('LC', 'Saint Lucia', 'Сент-Люсия'),
('LI', 'Liechtenstein', 'Лихтенштейн'),
('LK', 'Sri Lanka', 'Шри-Ланка'),
('LR', 'Liberia', 'Либерия'),
('LS', 'Lesotho', 'Лесото'),
('LT', 'Lithuania', 'Литва'),
('LU', 'Luxembourg', 'Люксембург'),
('LV', 'Latvia', 'Латвия'),
('LY', 'Libya', 'Ливия'),
('MA', 'Morocco', 'Марокко'),
('MC', 'Monaco', 'Монако'),
('MD', 'Moldova (Republic of)', 'Молдавия'),
('ME', 'Montenegro', 'Черногория'),
('MF', 'Saint Martin (French part)', 'Сен-Мартен'),
('MG', 'Madagascar', 'Мадагаскар'),
('MH', 'Marshall Islands', 'Маршалловы Острова'),
('MK', 'Macedonia (the former Yugoslav Republic of)', 'Македония'),
('ML', 'Mali', 'Мали'),
('MM', 'Myanmar', 'Мьянма'),
('MN', 'Mongolia', 'Монголия'),
('MO', 'Macao', 'Макао'),
('MP', 'Northern Mariana Islands', 'Северные Марианские Острова'),
('MQ', 'Martinique', 'Snake  Мартиника'),
('MR', 'Mauritania', 'Мавритания'),
('MS', 'Montserrat', 'Монтсеррат'),
('MT', 'Malta', 'Мальта'),
('MU', 'Mauritius', 'Маврикий'),
('MV', 'Maldives', 'Мальдивы'),
('MW', 'Malawi', 'Малави'),
('MX', 'Mexico', 'Мексика'),
('MY', 'Malaysia', 'Малайзия'),
('MZ', 'Mozambique', 'Мозамбик'),
('NA', 'Namibia', 'Намибия'),
('NC', 'New Caledonia', 'Новая Каледония'),
('NE', 'Niger', 'Нигер'),
('NF', 'Norfolk Island', 'Остров Норфолк'),
('NG', 'Nigeria', 'Нигерия'),
('NI', 'Nicaragua', 'Никарагуа'),
('NL', 'Netherlands', 'Нидерланды'),
('NO', 'Norway', 'Норвегия'),
('NP', 'Nepal', 'Непал'),
('NR', 'Nauru', 'Науру'),
('NU', 'Niue', 'Ниуэ'),
('NZ', 'New Zealand', 'Новая Зеландия'),
('OM', 'Oman', 'Оман'),
('PA', 'Panama', 'Панама'),
('PE', 'Peru', 'Перу'),
('PF', 'French Polynesia', 'Французская Полинезия'),
('PG', 'Papua New Guinea', 'Папуа — Новая Гвинея'),
('PH', 'Philippines', 'Филиппины'),
('PK', 'Pakistan', 'Пакистан'),
('PL', 'Poland', 'Польша'),
('PM', 'Saint Pierre and Miquelon', 'Сен-Пьер и Микелон'),
('PN', 'Pitcairn', 'Острова Питкэрн'),
('PR', 'Puerto Rico', 'Пуэрто-Рико'),
('PS', 'Palestine, State of', 'Государство Палестина'),
('PT', 'Portugal', 'Португалия'),
('PW', 'Palau', 'Палау'),
('PY', 'Paraguay', 'Парагвай'),
('QA', 'Qatar', 'Катар'),
('RE', 'Reunion', 'Реюньон'),
('RO', 'Romania', 'Румыния'),
('RS', 'Serbia', 'Сербия'),
('RU', 'Russian Federation', 'Россия'),
('RW', 'Rwanda', 'Руанда'),
('SA', 'Saudi Arabia', 'Саудовская Аравия'),
('SB', 'Solomon Islands', 'Соломоновы Острова'),
('SC', 'Seychelles', 'Сейшельские Острова'),
('SD', 'Sudan', 'Судан'),
('SE', 'Sweden', 'Швеция'),
('SG', 'Singapore', 'Сингапур'),
('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'Острова Святой Елены, Вознесения и Тристан-да-Кунья'),
('SI', 'Slovenia', 'Словения'),
('SJ', 'Svalbard and Jan Mayen', 'Флаг Шпицбергена и Ян-Майена Шпицберген и Ян-Майен'),
('SK', 'Slovakia', 'Словакия'),
('SL', 'Sierra Leone', 'Сьерра-Леоне'),
('SM', 'San Marino', 'Сан-Марино'),
('SN', 'Senegal', 'Сенегал'),
('SO', 'Somalia', 'Сомали'),
('SR', 'Suriname', 'Суринам'),
('SS', 'South Sudan', 'Южный Судан'),
('ST', 'Sao Tome and Principe', 'Сан-Томе и Принсипи'),
('SV', 'El Salvador', 'Сальвадор'),
('SX', 'Sint Maarten (Dutch part)', 'Синт-Мартен'),
('SY', 'Syrian Arab Republic', 'Сирия'),
('SZ', 'Swaziland', 'Свазиленд'),
('TC', 'Turks and Caicos Islands', 'Тёркс и Кайкос'),
('TD', 'Chad', 'Чад'),
('TF', 'French Southern Territories', 'Французские Южные и Антарктические Территории'),
('TG', 'Togo', 'Того'),
('TH', 'Thailand', 'Таиланд'),
('TJ', 'Tajikistan', 'Таджикистан'),
('TK', 'Tokelau', 'Токелау'),
('TL', 'Timor-Leste', 'Восточный Тимор'),
('TM', 'Turkmenistan', 'Туркмения'),
('TN', 'Tunisia', 'Тунис'),
('TO', 'Tonga', 'Тонга'),
('TR', 'Turkey', 'Турция'),
('TT', 'Trinidad and Tobago', 'Тринидад и Тобаго'),
('TV', 'Tuvalu', 'Тувалу'),
('TW', 'Taiwan, Province of China[a]', 'Китайская Республика'),
('TZ', 'Tanzania, United Republic of', 'Танзания'),
('UA', 'Ukraine', 'Украина'),
('UG', 'Uganda', 'Уганда'),
('UM', 'United States Minor Outlying Islands', 'Внешние малые острова (США)'),
('US', 'United States of America', 'США'),
('UY', 'Uruguay', 'Уругвай'),
('UZ', 'Uzbekistan', 'Узбекистан'),
('VA', 'Holy See', 'Ватикан'),
('VC', 'Saint Vincent and the Grenadines', 'Сент-Винсент и Гренадины'),
('VE', 'Venezuela (Bolivarian Republic of)', 'Венесуэла'),
('VG', 'Virgin Islands (British)', 'Виргинские Острова (Великобритания)'),
('VI', 'Virgin Islands (U.S.)', 'Виргинские Острова (США)'),
('VN', 'Viet Nam', 'Вьетнам'),
('VU', 'Vanuatu', 'Вануату'),
('WF', 'Wallis and Futuna', 'Уоллис и Футуна'),
('WS', 'Samoa', 'Самоа'),
('YE', 'Yemen', 'Йемен'),
('YT', 'Mayotte', 'Майотта'),
('ZA', 'South Africa', 'ЮАР'),
('ZM', 'Zambia', 'Замбия'),
('ZW', 'Zimbabwe', 'Зимбабве');